name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Customize breakout colors
        run: |
          sed -i 's/fill="#1F6FEB"/fill="#FAA627"/g' images/breakout-light.svg
          sed -i 's/fill="#1F6FEB"/fill="#FAA627"/g' images/breakout-dark.svg

          sed -i 's/fill="#1F6FEB"/fill="#FAA627"/g' images/breakout-light.svg
          sed -i 's/fill="#1F6FEB"/fill="#FAA627"/g' images/breakout-dark.svg          

      - name: Update branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Commit and push SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/breakout-light.svg images/breakout-dark.svg
          git diff --staged --quiet || git commit -m "chore: update breakout SVGs"
          git push
